# Generated by Django 5.1 on 2024-08-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordstorage',
            name='stored_password',
            field=models.CharField(max_length=150),
        ),
    ]
